### ISSUE TITLE
Tela da Página Inicial 

### ISSUE THREAD

**Issue by hi-hi-ray** [Infnet-SJ90/sj90.github.io#3]

**Comment by larismourullo** [comment]
Página Inicial:
![home](https://user-images.githubusercontent.com/20982222/42136562-414c8286-7d34-11e8-9ddb-836190b6aea8.png)

Algumas configurações que precisarão ser feitas:
![home - css](https://user-images.githubusercontent.com/20982222/42136566-4e897c6a-7d34-11e8-91df-238bc9a867e3.png)
